### PR TITLE
add multiple support

### PR DESCRIPTION
**Pull request by excaliburhan**
### multiple handlers

I need multiple handlers for different repos and I hope those handlers have different secret for each repo. And those handlers only take one port.

So I make `options.secret` to support both string and object. If `options.secret` is an object, the key of the object will be `appId`, and the value of the object will be `appSecret`. At last, the `EmitData` will return the `appId` for use.

---

Here's the example for multiple handlers:

```js
// handler settings
var handler = createHandler({
  path: '/app',
  secret: {
    app1: 'secret1',
    app2: 'secret2'
  }
})
// server
http.createServer(function (req, res) {
  handler(req, res, function (err) {
    res.statusCode = 404
    res.end('no such location')
  })
}).listen(7777)
// events
handler.on('push', function (event) {
  var appId = event.appId
  switch (appId) {
    case 'app1':
      // do sth about app1
      break
    case 'app2':
      // do sth about app2
      break
    default:
      break
  }
})
```

And in github Webhooks Payload URL:

app1
```
http://example.com/app?id=app1
```

app2
```
http://example.com/app?id=app2
```

---

If `options.secret` is a string, everything remains the same.

### CODE REVIEW

**Comment by rjz** [comment]
Thanks, @excaliburhan! This PR covers a fairly specific scenario as written, but I wonder if we could expand it to accommodate the scenarios in #16 ("add additional fields to `emitData`") and #21 ("enable multiple handlers").

If we allowed consumers to provide their own validation/parsing logic--or even separated webhook processing from the HTTP server itself--we could preserve the existing (simple) default but open the door for more customization downstream.

Thoughts?

**Comment by excaliburhan** [comment]
OK, I realize this PR is actually 'One handler deals with multiple webhooks'.

Solution A: expand
Support multiple path && secret to enable real multiple handlers, like this:

```js
var createHandler = require('github-webhook-handler')
var handler = createHandler([
{ path: '/app1', secret: 'secret1' },
{ path: '/app2', secret: 'secret2' }
])
```

this solution means we have to rewrite the `handler` function in `github-webhook-handler.js`

---

Solution B: process over the HTTP server 

```js
var handlerA = createHandler({ path: '/app1', secret: 'secret1' })
var handlerB = createHandler({ path: '/app2', secret: 'secret2' })

http.createServer(function (req, res) {
  // process logic
  switch (req.url) {
    case '/app1':
      handlerA(req, res, function (err) {
        res.statusCode = 404
        res.end('no such location')
      })
      break
    case '/app2':
      handlerB(req, res, function (err) {
        res.statusCode = 404
        res.end('no such location')
      })
      break
    default:
      break
  }
}).listen(7777)

// events
handlerA.on('issues', function(event) {
    // do sth
})
handlerB.on('issues', function(event) {
    // do sth
})
```

this solution contains consumers' own process logic.

---

I prefer the Solution A, it may make the `github-webhook-handler.js` a little complicated, but for consumers, it's more convenient.

For Solution B, what makes me unhappy is I have to write many nearly same code to keep different handlers work.

I'd like to help with Solution A.

@rjz what you think about this?

**Comment by rjz** [comment]
It seems like we could write A in terms of B, something like:

```js
function multiHook(handlerOpts) { // it's a silly name :^)
  var handlers = handlerOpts.reduce(function (hs, opts) {
    hs[opts.path] = createHandler(opts);
    return hs;
  }, {});

  return http.createServer(function (req, res) {
    var handler = handlers[req.url];
    handler(req, res, function (err) {
      res.statusCode = 404
      res.end('no such location')
    });
  });
}
```

If that's reasonable, maybe it's appropriate to leave this handler focused on a single hook but either:

  - add an example for the multi-app case here
  - create a new package (ala [github-webhook](https://github.com/rvagg/github-webhook)) tailored to the multi-app case

**Comment by excaliburhan** [comment]
Cool.
I think we could close this PR now:)

**Comment by excaliburhan** [comment]
One more thing, in github webhooks settings, the `content-type` must be `application/json` rather than `application/x-www-form-urlencoded`.

I think this tip should be written in the READEME.md.

Just a suggestion.

**Comment by rjz** [comment]
Done, and big thanks for your suggestions on this, @excaliburhan!

  - README.md: great point, will add (or be happy to merge a PR)
  - Also, if you're up to add an example to this repo or to link up an external package, it would be awesome to have a reference for other folks with this issue

**Comment by excaliburhan** [comment]
ok, here's the multi handlers complete example(have tested on my server), and an external package [node-github-webhook](https://github.com/excaliburhan/node-github-webhook).

### example for github-webhook-handler

```js
function generaterHandler(handlerOpts) {
  var handlers = handlerOpts.reduce(function(hs, opts) {
    hs[opts.path] = createHandler(opts)
    return hs
  }, {})

  return http.createServer(function(req, res) {
    var handler = handlers[req.url]
    handler(req, res, function(err) {
      res.statusCode = 404
      res.end('no such location')
    })
  }).listen(7777)
}

var http = require('http')
var createHandler = require('github-webhook-handler')
var handlerOpts = [{
  path: '/app1',
  secret: 'secret1'
}, {
  path: '/app2',
  secret: 'secret2'
}]
var handler = generaterHandler(handlerOpts)

handler.on('error', function(err) {
  console.error('Error:', err.message)
})
handler.on('push', function (event) {
  console.log('Received a push event for %s to %s',
    event.payload.repository.name,
    event.payload.ref)
})
```

### example for node-github-webhook

```js
var http = require('http')
var createHandler = require('node-github-webhook')
var handler = createHandler([{
    path: '/app1',
    secret: 'secret1'
  },
  {
    path: '/app2',
    secret: 'secret2'
  }
])

http.createServer(function (req, res) {
  handler(req, res, function (err) {
    res.statusCode = 404
    res.end('no such location')
  })
}).listen(7777)

// handler
handler.on('error', function (err) {
  console.error('Error:', err.message)
})
handler.on('push', function (event) {
  var path = event.path
  switch (path) {
    case '/app1':
      // do sth for app1
      break
    case '/app2':
      // do sth for app2
      break
    default:
      break
  }
})
```

**Pull request closed without merging**
